image: gitpod/workspace-postgres
tasks:
  - name: Backend
    init: |
      cd server
      pip install -r requirements.txt
      cat >.env <<EOF
      SECRET_KEY=oiwnewerJlw70238974
      ENV=development
      POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
      POSTGRES_HOST=localhost
      POSTGRES_PORT=5432
      POSTGRES_DATABASE=postgres
      POSTGRES_USER=gitpod
      EOF
      python manage.py makemigrations
      python manage.py migrate
      python manage.py shell <<EOF
      from messenger_backend.seed import seed
      seed()
      exit()
      EOF
    command: python manage.py runserver
  - name: Frontend
    init: |
      cd client
      npm install
    command: DANGEROUSLY_DISABLE_HOST_CHECK=true npm start
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 8000
    onOpen: notify
    visibility: public
  - port: 5432
    onOpen: ignore
    visibility: private
